import type { Metadata } from "next";
import { Orbitron, Saira } from "next/font/google";
import "./global.css";

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron", // 👈 CSS variable for Orbitron
  weight: ["400", "700"], // you can customize weights
});

const saira = Saira({
  subsets: ["latin"],
  variable: "--font-saira", // 👈 CSS variable for Saira
  weight: ["400", "600"], // adjust as needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${orbitron.variable} ${saira.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
